package org.telegram.messenger;

import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.Keep;

import com.chaquo.python.Python;

import org.json.JSONArray;
import org.json.JSONObject;
import org.mvel2.MVEL;
import org.telegram.tgnet.TLRPC;
import org.telegram.ui.ActionBar.ActionBarMenuItem;
import org.telegram.ui.ActionBar.ActionBarMenuSubItem;
import org.telegram.ui.ActionBar.ActionBarPopupWindow;
import org.telegram.ui.ActionBar.BaseFragment;
import org.telegram.ui.Components.ItemOptions;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.WeakHashMap;

/** Native presentation only. Python owns registrations and callback lifetime. */
@Keep
public final class WgtgPluginMenus {
    public static final int MESSAGE_CONTEXT_MENU = 0;
    public static final int DRAWER_MENU = 1;
    public static final int MAIN_MENU = 2;
    public static final int CHAT_ACTION_MENU = 3;
    public static final int PROFILE_ACTION_MENU = 4;

    // UI thread only; a dismissed menu must not keep its fragment alive here.
    private static final WeakHashMap<View, String> rows = new WeakHashMap<>();

    private WgtgPluginMenus() {}

    public static HashMap<String, Object> context(BaseFragment fragment, long dialogId,
            TLRPC.User user, TLRPC.Chat chat, TLRPC.UserFull userFull, TLRPC.ChatFull chatFull,
            TLRPC.EncryptedChat encryptedChat, MessageObject message, Object groupedMessages, Object botInfo) {
        HashMap<String, Object> result = new HashMap<>();
        result.put("account", fragment.getCurrentAccount());
        result.put("context", fragment.getContext());
        result.put("fragment", fragment);
        result.put("dialog_id", dialogId);
        result.put("user", user);
        result.put("userId", user == null ? 0L : user.id);
        result.put("userFull", userFull);
        result.put("chat", chat);
        result.put("chatId", chat == null ? 0L : chat.id);
        result.put("chatFull", chatFull);
        result.put("encryptedChat", encryptedChat);
        result.put("message", message);
        result.put("groupedMessages", groupedMessages);
        result.put("botInfo", botInfo);
        return result;
    }

    public static HashMap<String, Object> context(BaseFragment fragment) {
        return context(fragment, 0, null, null, null, null, null, null, null, null);
    }

    public static boolean evaluateCondition(String expression, Map<String, Object> context) {
        // Interpreted evaluation avoids MVEL's generated bytecode optimizer on Android.
        return Boolean.TRUE.equals(MVEL.evalToBoolean(expression, new HashMap<>(context)));
    }

    private static JSONArray items(int type, HashMap<String, Object> context) {
        if (!WgtgPluginsController.isReady()) return new JSONArray();
        try {
            return new JSONArray(Python.getInstance().getModule("plugin_menus")
                    .callAttr("visible_items", type, context).toJava(String.class));
        } catch (Throwable e) {
            FileLog.e(e);
            return new JSONArray();
        }
    }

    private static void click(String token, HashMap<String, Object> context) {
        if (!WgtgPluginsController.isReady()) return;
        BaseFragment fragment = (BaseFragment) context.get("fragment");
        if (fragment == null || fragment.getParentActivity() == null || fragment.isFinished) return;
        if (fragment.getCurrentAccount() != ((Number) context.get("account")).intValue()) return;
        try {
            Python.getInstance().getModule("plugin_menus").callAttr("click", token, context);
        } catch (Throwable e) {
            FileLog.e(e);
        }
    }

    private static ActionBarMenuSubItem row(BaseFragment fragment, JSONObject item,
            HashMap<String, Object> context, Runnable dismiss) throws Exception {
        String token = item.getString("token");
        ActionBarMenuSubItem row = new ActionBarMenuSubItem(fragment.getContext(), false, false, fragment.getResourceProvider());
        String icon = item.isNull("icon") ? "" : item.optString("icon", "");
        int drawable = icon.isEmpty() ? 0 : fragment.getContext().getResources()
                .getIdentifier(icon, "drawable", ApplicationLoader.applicationContext.getPackageName());
        row.setTextAndIcon(item.getString("text"), drawable);
        row.setMinimumWidth(AndroidUtilities.dp(200));
        String subtext = item.isNull("subtext") ? "" : item.optString("subtext", "");
        if (!subtext.isEmpty()) {
            row.setSubtext(subtext);
            row.setItemHeight(56);
        }
        row.setOnClickListener(view -> {
            dismiss.run();
            click(token, context);
        });
        rows.put(row, token);
        return row;
    }

    /** Call from onShowSubMenu, after lazy native rows have been materialized. */
    public static void populate(ActionBarMenuItem menu, int type, BaseFragment fragment, HashMap<String, Object> context) {
        ActionBarPopupWindow.ActionBarPopupWindowLayout layout = menu.getPopupLayout();
        for (int i = layout.getItemsCount() - 1; i >= 0; i--) {
            View child = layout.getItemAt(i);
            if (rows.remove(child) != null) {
                child.setOnClickListener(null);
                ((ViewGroup) child.getParent()).removeView(child);
            }
        }
        append(layout, type, fragment, context, menu::closeSubMenu);
    }

    public static void append(ActionBarPopupWindow.ActionBarPopupWindowLayout layout, int type,
            BaseFragment fragment, HashMap<String, Object> context, Runnable dismiss) {
        JSONArray items = items(type, context);
        for (int i = 0; i < items.length(); i++) {
            try {
                layout.addView(row(fragment, items.getJSONObject(i), context, dismiss));
            } catch (Throwable e) {
                FileLog.e(e);
            }
        }
    }

    public static void append(ItemOptions options, int type, BaseFragment fragment, HashMap<String, Object> context) {
        JSONArray items = items(type, context);
        for (int i = 0; i < items.length(); i++) {
            try {
                options.add(row(fragment, items.getJSONObject(i), context, options::dismiss));
            } catch (Throwable e) {
                FileLog.e(e);
            }
        }
    }

    /** Called by Python after removal; queued so background unload never touches views. */
    public static void invalidate(String tokensJson) {
        AndroidUtilities.runOnUIThread(() -> {
            try {
                JSONArray tokens = new JSONArray(tokensJson);
                HashSet<String> removed = new HashSet<>();
                for (int i = 0; i < tokens.length(); i++) removed.add(tokens.getString(i));
                rows.entrySet().removeIf(entry -> {
                    if (!removed.contains(entry.getValue())) return false;
                    View row = entry.getKey();
                    if (row != null) {
                        row.setOnClickListener(null);
                        row.setVisibility(View.GONE);
                        if (row.getParent() instanceof ViewGroup) ((ViewGroup) row.getParent()).removeView(row);
                    }
                    return true;
                });
            } catch (Throwable e) {
                FileLog.e(e);
            }
        });
    }
}
